---
title: "beginning_stats"
output:
  html_document:
    code_folding: hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown for begnning the statistical analysis for sonobuoy honours

Readinging in the data
```{r}
ifile = readRDS("data/processed/proc_acou_photoid.rds")
df1= ifile
```


```{r, include=FALSE}
#Some useful libraries for plotting
library(tidyverse)
library(viridis)
library(ggplot2)
library(dplyr)
library(lubridate)
library(grid)
library(plotly)
library(RColorBrewer)
library(oce)
library(xtable)
library(mapproj)

#library(gganimate)
#source('D:/narw_sonobuoys/functions.R')
```

## Maps with calls and behaviour as size {.tabset}
### Up calls 
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# up production rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = up_per_hr_per_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl

```

### Gunshots
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# gs production rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = gs_per_hr_per_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl

```

### Mid-frequency
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# mf production rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = mf_per_hr_per_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl

```

### Feeding behaviour
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# foraging rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = foraging_bhv_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl
```

### Social behaviour
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# socalizing rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = social_bhv_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl

```

### Other behaviour
```{r,fig.width=10,fig.height=11}
# read in map data
load('data/processed/map_data.rda')

# other behaviour rate
# city positions
cities = data.frame(
  name = c("Shippagan", "Percé",'OT'),
  lat = c(47.7439, 48.5244,47.90),
  lon = c(-64.7057,-64.2127,-63.90)
)

# gsl map
gsl = ggplot() +
  coord_map(xlim = c(-65,-62), ylim = c(47.2, 48.8)) +
  
  # land and bathymetry
  geom_polygon(
    data = nam,
    aes(x = long, y = lat, group = group),
    fill = "darkgrey",
    color = NA
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-50),
    colour = "grey",
    size = 0.3
  ) +
  geom_contour(
    data = bf,
    aes(x = x, y = y, z = z),
    breaks = c(-100),
    colour = "grey",
    size = 1
  ) +
  
  # city labels
  geom_point(data = cities,
             aes(x = lon, y = lat),
             color = "darkslategrey",
             size = 1) +
  geom_text(
    data = cities,
    aes(x = lon, y = lat, label = name),
    color =
      "darkslategrey",
    nudge_y = 0.07,
    size = 3
  ) +
  
  # sonobuoy positions
  geom_point(data = df1,
             aes(x = lon,
                 y = lat,
                 colour = other_bhv_whale)) + #, colour = yday)) +
  #scale_colour_continuous(type = "viridis")+
  # scale_fill_viridis_c(guide = guide_colourbar(barheight = 15,
  #                                              title.theme = element_text(angle=90),
  #                                              title.position = 'right', 
  #                                              title.hjust = 0.5))+
  #scale_fill_continuous(type = "viridis")+
  #scale_colour_viridis(guide='colourbar') +
  scale_colour_viridis() +
  scale_radius(range = c(3, 8)) +
  
  labs(x = "Latitude (W)", 
       y = "Longitude (N)")+
  #guides(colour=guide_legend(title="Rate"))+
  
  # facet by year
  #facet_wrap(~myear)+
  facet_grid(year ~ month) +
  
  # formatting
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.position = 'bottom',
    legend.direction = "horizontal",
    panel.spacing = unit(2, "lines")
  ) +
  theme(text = element_text(size = 15)) +
  theme(axis.text.x = element_text(colour = "black")) +
  theme(axis.text.y = element_text(colour = "black"))

gsl

```

